"""Added subtasks for 6, 7, 8 in grades

Revision ID: afb56bd21e95
Revises: 1a58efbe54d3
Create Date: 2025-04-08 18:54:12.642838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb56bd21e95'
down_revision: Union[str, None] = '1a58efbe54d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('task_6_a', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_6_b', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_6_c', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_7_a', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_7_b', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_7_c', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_8_a', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_8_b', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('task_8_c', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'task_8_c')
    op.drop_column('grades', 'task_8_b')
    op.drop_column('grades', 'task_8_a')
    op.drop_column('grades', 'task_7_c')
    op.drop_column('grades', 'task_7_b')
    op.drop_column('grades', 'task_7_a')
    op.drop_column('grades', 'task_6_c')
    op.drop_column('grades', 'task_6_b')
    op.drop_column('grades', 'task_6_a')
    # ### end Alembic commands ###
